### ISSUE TITLE
Compatibility with Vanilla

### ISSUE THREAD

**Issue by JacobH140** [JosephEoff/PureData_NoiseFilter#1]
Hi there! 

I noticed this patch was developed around 6 years ago, and am having some trouble instantiating some of the objects in Pd Vanilla - was the patch created in Pd Extended? If so, what externals should be installed?

Thank you so much!
Jake

**Comment by JosephEoff** [comment]
Hello Jacob.

Yes, my PureData NoiseFilter was made with Pd Extended.  I'll have to look and see which parts I used.  Mostly high order Butterworth filters, I think.

I'll update the ReadMe with information on which externals are needed.

In the mean time, you might try [PurrData](https://github.com/agraef/purr-data/releases) - it seems to be a sort of successor to Pd Extended.

**Comment by JosephEoff** [comment]
I've updated the ReadMe.

Please check and see if you can get it running with the additional information in the ReadMe.
Let me know if I've forgotten (or missed) any of the externals.

**Comment by JacobH140** [comment]
Nope, those two libraries were all it needed. Thank you so much!
